"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { BookingStatus, Role } from "@/generated/prisma/enums";

export function RescheduleActions({ bookingId, status, startAt, serviceSlug, currentStaffId, role }: { bookingId: string; status: BookingStatus; startAt: string; serviceSlug: string; currentStaffId: string; role: Role }) {
  const router = useRouter(); const [date, setDate] = useState(""); const [staffId, setStaffId] = useState(currentStaffId); const [slots, setSlots] = useState<Array<{ startAt: string; localTimeLabel: string }>>([]); const [selected, setSelected] = useState(""); const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  async function load() { setPending(true); setMessage(""); try { const staff = staffId ? `&staff=${staffId}` : ""; const response = await fetch(`/api/availability?service=${serviceSlug}&date=${date}${staff}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) return setMessage(body.error || "Availability could not be loaded."); setSlots(body.slots); } catch { setMessage("Availability could not be loaded."); } finally { setPending(false); } }
  async function save() { setPending(true); setMessage(""); try { const response = await fetch(`/api/admin/appointments/${bookingId}/reschedule`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedStatus: status, expectedStartAt: startAt, startAt: selected, ...(staffId ? { staffId } : {}), note }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error || "Appointment could not be rescheduled."); setMessage("Appointment rescheduled."); setSelected(""); setSlots([]); router.refresh(); } catch { setMessage("Appointment could not be rescheduled."); } finally { setPending(false); } }
  return <div><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">New date<input className="mt-2 min-h-11 w-full rounded-xl border border-ink/20 px-3" onChange={(event) => setDate(event.target.value)} type="date" value={date} /></label>{role === "ADMIN" ? <label className="text-sm font-semibold">Professional<select className="mt-2 min-h-11 w-full rounded-xl border border-ink/20 px-3" onChange={(event) => setStaffId(event.target.value)} value={staffId}><option value={currentStaffId}>Current professional</option><option value="">Any available</option></select></label> : <p className="mt-7 text-sm">Staff rescheduling remains assigned to you.</p>}<button className="mt-6 min-h-11 rounded-full bg-ink px-5 font-semibold text-cream disabled:opacity-50" disabled={!date || pending} onClick={load} type="button">Check times</button></div>{slots.length ? <div className="mt-4 flex flex-wrap gap-2">{slots.map((slot) => <button className={`min-h-11 rounded-full border px-4 ${selected === slot.startAt ? "bg-sage text-cream" : "border-ink/20"}`} key={slot.startAt} onClick={() => setSelected(slot.startAt)} type="button">{slot.localTimeLabel}</button>)}</div> : null}{selected ? <div className="mt-5"><label className="text-sm font-semibold">Internal note (optional)<input className="mt-2 min-h-11 w-full rounded-xl border border-ink/20 px-3" maxLength={1000} onChange={(event) => setNote(event.target.value)} value={note} /></label><button className="mt-4 min-h-11 rounded-full bg-sage px-5 font-semibold text-cream disabled:opacity-50" disabled={pending} onClick={save} type="button">Confirm reschedule</button></div> : null}<p aria-live="polite" className="mt-4 text-sm font-semibold text-clay">{message}</p></div>;
}

